// <auto-generated />
using Blog.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Blog.WebApi.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20190724020246_InitialDbase")]
    partial class InitialDbase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blog.WebApi.Models.BlogItem", b =>
                {
                    b.Property<int>("BlogItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rating");

                    b.Property<string>("Url");

                    b.HasKey("BlogItemId");

                    b.ToTable("BlogItems");
                });

            modelBuilder.Entity("Blog.WebApi.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlogItemId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("BlogPostId");

                    b.HasIndex("BlogItemId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("Blog.WebApi.Models.BlogPost", b =>
                {
                    b.HasOne("Blog.WebApi.Models.BlogItem", "BlogItem")
                        .WithMany("BlogPosts")
                        .HasForeignKey("BlogItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
